name: 'dbt_crypto'
version: '1.0.0'
profile: 'dbt_crypto'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_crypto:
    staging:
      +materialized: table
    marts:
      +materialized: table
